apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql2deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql2app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql2
        image: microsoft/mssql-server-linux
        ports:
        - containerPort: 1433
        securityContext:
          privileged: true
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql2mount
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql2mount
        persistentVolumeClaim:
          claimName: mssql2pvc